### ISSUE TITLE
[BUG] preset.getSamplesAndGenerators is not a function

### ISSUE THREAD

**Issue by bastecklein** [spessasus/SpessaSynth#12]
I was playing around with SpessaSynth last week following the "Using as a library" instructions, and was able to load the Sound Font parser and Synthetizer and play arbitrary notes from different sound fonts without issue.

This morning I noticed you had updated the library so I downloaded the latest code to try it out.  I now get the following error when calling synth.noteOn, with no other changes to my code:

![Screenshot 2024-06-17 06 36 07](https://github.com/spessasus/SpessaSynth/assets/8765220/5912470f-fd02-498e-b826-92f1bcc1a739)

I was not sure if there has been a change to the way the library is used or not.  

Anyway, this is a cool project, I was having fun playing around with it!

**Comment by bastecklein** [comment]
Never mind, I found out that you now initialize the Synthetizer with an ArrayBuffer of the sound font instead of a SoundFont2 object as before.  Seems to be working fine now.  Sorry!

**Comment by spessasus** [comment]
Hi,
Sorry for not updating the documentation earlier. I'm glad that you managed to figure it out yourself : )

**Comment by spessasus** [comment]
Essentially there was a complete internal rewrite that moved everything into the global scope and allowed offline audio rendering, and some methods had to be changed. If you notice any other documentation errors, feel free to open another issue.
