### ISSUE TITLE
Limit voices to 100 on mobile

### ISSUE THREAD

**Issue by spessasus** [spessasus/SpessaSynth#17]
Blame Chromium's web audio Implementation not me

**Comment by bastecklein** [comment]
Just want to say that out of the blue you have created the best JS MIDI library on the web.  Thank  you so much!

**Comment by spessasus** [comment]
Thank you, @bastecklein! I really appreciate your comment. I'm trying my best to make this library as good as possible. Starring this repo would be appreciated too : )
