### ISSUE TITLE
How to monitor the end of mid play?

### ISSUE THREAD

**Issue by LiHongyao** [spessasus/SpessaSynth#25]
I use it in react, I don't know how to monitor the end of mid play, can you tell me how to achieve it? Thank you!

**Comment by spessasus** [comment]
Hi @LiHongyao,

I think the easiest way for detecting when the song has ended (assuming the loop is disabled) is by checking if the currentTime property of the sequencer is equal or larger than the duration property.

Although I can add a new event to the sequencer called `addOnSogEndEvent` if you'd like!

**Comment by LiHongyao** [comment]
> Hi @LiHongyao,
> 
> I think the easiest way for detecting when the song has ended (assuming the loop is disabled) is by checking if the currentTime property of the sequencer is equal or larger than the duration property.
> 
> Although I can add a new event to the sequencer called `addOnSogEndEvent` if you'd like!

Thank you very much for your suggestion. If possible, I think adding addOnSogEndEvent is a very meaningful thing. Looking forward to your update, thank you again!

**Comment by spessasus** [comment]
I've added the [onSongEnded event!](https://github.com/spessasus/SpessaSynth/wiki/Sequencer-Class#addonsongendedevent) I hope this helps.

Also, spessasynth_lib is [now available as an npm package!](https://www.npmjs.com/package/spessasynth_lib).
This can be helpful since you use react.

**Comment by LiHongyao** [comment]
Thank you very much, you’re awesome! Now I have a question that might not be directly related to this library, but I would still like to ask for your help. My current project is quite old and was created using create-react-app. The project’s webpack version is likely v4.x, which causes it to not recognize import.meta.url, resulting in the following console error:

index.js:1211 ./node_modules/spessasynth_lib/synthetizer/audio_effects/reverb.js 16:62
Module parse failed: Unexpected token (16:62)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } else {
|     // resolve relative url
>     var impulseURL = new URL("impulse_response_2.flac", import.meta.url);
|     fetch(impulseURL).then( /*#__PURE__*/function () {
|       var _ref = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime().mark(function _callee(response) {

Could you possibly make the line var impulseURL = new URL("impulse_response_2.flac", import.meta.url); backward compatible? Or do I have a better solution?

**Comment by LiHongyao** [comment]
Thank you very much, you’re awesome! Now I have a question that might not be directly related to this library, but I would still like to ask for your help. My current project is quite old and was created using create-react-app. The project’s webpack version is likely v4.x, which causes it to not recognize import.meta.url, resulting in the following console error:

`index.js:1211 ./node_modules/spessasynth_lib/synthetizer/audio_effects/reverb.js 16:62
Module parse failed: Unexpected token (16:62)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } else {
|     // resolve relative url
>     var impulseURL = new URL("impulse_response_2.flac", import.meta.url);
|     fetch(impulseURL).then( /*#__PURE__*/function () {
|       var _ref = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime().mark(function _callee(response) {`


Could you possibly make the line  ` var impulseURL = new URL("impulse_response_2.flac", import.meta.url);`  backward compatible? Or do I have a better solution?

**Comment by LiHongyao** [comment]
Thank you very much, you’re awesome! Now I have a question that might not be directly related to this library, but I would still like to ask for your help. My current project is quite old and was created using create-react-app. The project’s webpack version is likely v4.x, which causes it to not recognize import.meta.url, resulting in the following console error:

`
index.js:1211 ./node_modules/spessasynth_lib/synthetizer/audio_effects/reverb.js 16:62
Module parse failed: Unexpected token (16:62)
File was processed with these loaders:

./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| } else {
| // resolve relative url
| var impulseURL = new URL("impulse_response_2.flac", import.meta.url);
| fetch(impulseURL).then( /#PURE/function () {
| var _ref = _asyncToGenerator( /#PURE/_regeneratorRuntime().mark(function _callee(response) {`

Could you possibly make the line  var impulseURL = new URL("impulse_response_2.flac", import.meta.url); backward compatible? Or do I have a better solution?
