### ISSUE TITLE
Is it possible to disable trimming of MIDI's Synthetizer or Sequencer?

### ISSUE THREAD

**Issue by WickyPlays** [spessasus/SpessaSynth#27]
**Is your feature request related to a problem? Please describe.**
I've currently ran into the problem with my .mid file that has the first note at 30s in, the player proceed to skip the first 30s upon `seq.play()`.

**Describe the solution you'd like**
Add a way to toggle in sequencer where when playing, it needs to keep the 30s delay since there's no actual way in the library to do it. Even tried with `seq.currentTime = 0` to no avail.

Thank you for the awesome library though.

**Comment by spessasus** [comment]
Hi,
Try parsing the midi file and setting `yourParsedMidi.loop.start` to 0. It should work. If not, please provide the file and I'll try to add that functionality.

**Comment by spessasus** [comment]
My bad, you should set `firstNoteOn` to 0 for it to not skip anything.

**Comment by WickyPlays** [comment]
> My bad, you should set `firstNoteOn` to 0 for it to not skip anything.

Oh okay, forgot about that class lol. Thanks though.

**Comment by spessasus** [comment]
I've added this functionality. Check the wiki page  for the sequencer!
