### ISSUE TITLE
Control channel pan

### ISSUE THREAD

**Issue by Fanelia82** [spessasus/SpessaSynth#31]
### Documentation Confirmation
*Please confirm that you have read the [documentation](https://github.com/spessasus/SpessaSynth/wiki) and have not found an answer to your question there.*

YES

### Question's Topic
The problem regard the use of the lib

### The Question
Hi,
I'm using spessasynth in my project.
I m trying to modify pan for every channel (not setMasterPan) but i fail to find the correct way.
Please help!

thanks

**Comment by spessasus** [comment]
Hi Fanelia.
Try using the **[pan controller. (CC 10)](https://nickfever.com/music/midi-cc-list)**

```js
synth.controllerChange(channel, 10, value);
```
where 0 = left, 64 = center, 127 = right.

Hope this helps!

**Comment by Fanelia82** [comment]
Thanks!

Great work!
