### ISSUE TITLE
[BUG] wrong package import

### ISSUE THREAD

**Issue by bxclib2** [spessasus/SpessaSynth#39]
### Version
npm installed

### Description
There are two wrong imports in the index js. The correct one should be like:

import { modulatorSources } from './soundfont/read_sf2/modulators.js';
import { trimSoundfont } from './soundfont/basic_soundfont/write_sf2/soundfont_trimmer.js';

### Reproduction steps
*Describe the steps to reproduce the behavior.*

### Expected behavior
*Provide a clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### MIDI files and SoundFonts
*If the issue only persists with specific MIDIs or SoundFonts, add them here too. (preferably .zip)*

### Environment
*If the issue only persists on a smartphone, or only on a PC, or only on Chrome, etc. please specify.*

### Additional context
*Add any other context about the problem here that may be helpful.*

**Comment by spessasus** [comment]
Sorry, my bad! Fixed in 3.16.4

Also make sure to update `worklet_processor.min.js` in your project :-)

**Comment by bxclib2** [comment]
> Sorry, my bad! Fixed in 3.16.4
> 
> 
> 
> Also make sure to update `worklet_processor.min.js` in your project :-)

Thanks a lot for your quick reply!
