### ISSUE TITLE
[QUESTION] Support duration in the noteon function

### ISSUE THREAD

**Issue by bxclib2** [spessasus/SpessaSynth#40]
### Documentation Confirmation
*Please confirm that you have read the [documentation](https://github.com/spessasus/SpessaSynth/wiki) and have not found an answer to your question there.*

**Yes**

### Question's Topic
 `spessasynth_lib` 

### The Question
Hi, first thanks for the awesome lib. I have a small question. I see it seems for the backend synthesiser like fluid synth, it can support the duration in the "note on" function.  

It has a loop mode, so it can play the soundfont's sustain time indefinitely. (The time between the green line and red line)
<img width="715" alt="Screenshot 2024-08-20 at 4 23 42 PM" src="https://github.com/user-attachments/assets/3f72a70b-05eb-4c99-a7b3-287a2b5d6a1d">

Is this supported in the library? Would it useful for synthesising a long note in the midi (It seems for now, the library just trigger the note one time and let it decay by time no matter how long the note is. Is this accurate enough for the playing of the long note? I am a newbie in music and i checked the code only. Please correct me if i am wrong.)?

Thanks for the help!!

**Comment by spessasus** [comment]
Yes, it is supported. Both looping and decay. If your soundfont sets decay to a really high value (like 144 seconds) the note will keep playing even after note-off. It depends on your soundfont.

**Comment by spessasus** [comment]
For example, if you start a note with patch 80 (square) in the bundled soundfont it will keep playing until you send a note-off.

**Comment by bxclib2** [comment]
Hi, thanks for the reply. May i know is there a example that i can refer to? i check the doc here: https://github.com/spessasus/SpessaSynth/wiki/Synthetizer-Class#noteon but i see noteon has only very limit params. May i know where i can get the info for loop and decay?

**Comment by spessasus** [comment]
You _can't_ see that info. It's internal. I'm not sure why would you even want to see it. To keep playing the sample, simply send a note-on and don't send a note off on a patch that loops (flute for example) and it will keep playing (be looped)

If you really want to see each sample's loop points though, you must use the SoundFont2 class. It has a property called `samples` and each sample has a defined loop start and loop end. It's documented in the wiki.

**Comment by bxclib2** [comment]
for my understanding, there are four phase of sound: 1 Attack，2 Decay 3 Sustain 4 Release

If noteon is triggered, Attack Decay and Sustain will happen. For some midi program, Sustain is a constant phase. It has no decay. But this is not real. For real piano, even do not note off, the sound will decay little by little. Some advanced program can work like this.

if noteoff is triggered, a huge decay will enforce to the sound. It is the release phase. The sound will usually decay to zero very fast.

I tested your example program, like the real piano, the sound will disappear finally even i do not noteoff. This is nice i think but i just do not know where i can set this "loop time" and "slow decay" factor, to change 1 how much loop sustain time we have 2 how long sustain will go to zero (even i do not noteoff).

Please correct me if i am wrong since i am totally a rookie in music... Thanks a lot for your great lib and generous help!

**Comment by spessasus** [comment]
To set the loops points, you have to edit the soundfont itself. I recommend Polyphone for that.

**Comment by bxclib2** [comment]
oh i see. Sorry i misunderstood. I thought it need to be set in the library but in fact those are params in the soundfont. Sorry for my stupid question. Thanks a lot!

**Comment by spessasus** [comment]
That's okay, this is what questions are for.
