### ISSUE TITLE
[ENCHANCEMENT] Create a MIDI file from scratch

### ISSUE THREAD

**Issue by bxclib2** [spessasus/SpessaSynth#41]
### Documentation Confirmation
*Please confirm that you have read the [documentation](https://github.com/spessasus/SpessaSynth/wiki) and have not found an answer to your question there.*

**Yes**

### Question's Topic
`spessasynth_lib`

### The Question
Is the midi parser in this library able to generate a brand new midi file, like the jsmidgen?
[jsmidgen](https://github.com/dingram/jsmidgen)

Some examples from jsmidgen like this. I checked the doc and code, it seems no off-the-shelf method to construct a brand new midi file and track. All I can think of is to generate a midi with other library and later use midi-parser of SpessaSynth to re-parse back to midi object of SpessaSynth.

```
var fs = require('fs');
var Midi = require('jsmidgen');

var file = new Midi.File();
var track = new Midi.Track();
file.addTrack(track);

track.addNote(0, 'c4', 64);
track.addNote(0, 'd4', 64);
track.addNote(0, 'e4', 64);
track.addNote(0, 'f4', 64);
track.addNote(0, 'g4', 64);
track.addNote(0, 'a4', 64);
track.addNote(0, 'b4', 64);
track.addNote(0, 'c5', 64);

fs.writeFileSync('test.mid', file.toBytes(), 'binary');
```

**Comment by spessasus** [comment]
Hi,
While this isn't currently possible, this looks like a very simple addition.
Thanks for the idea, I'll work on it now!

**Comment by spessasus** [comment]
Hi, I've added the MIDI Builder class:
https://github.com/spessasus/SpessaSynth/wiki/Creating-MIDI-Files

I hope this was the feature you were looking for!

**Comment by bxclib2** [comment]
Yep, this is what I need. Thanks for your reply. Is this included in the npm library or I need install from GitHub? I will have some tests

**Comment by spessasus** [comment]
Yes, I've added it to npm too. (I didn't forget index.js this time :-)

**Comment by bxclib2** [comment]
Thanks!! I will try and if I encounter some issues I will help report
