### ISSUE TITLE
[QUESTION] Colab project

### ISSUE THREAD

**Issue by asigalov61** [spessasus/SpessaSynth#49]
Hey @spessasus,

I apologize for posting it here, but you do not have any private contact info listed on your profile, and I wanted to ask you a question which is somewhat Spessasynth related...

I am trying to find people who can help me build a complete Symbolic Music AI implementation (frontend and backend). I could really use your skills and expertise in JavaScript and MIDI because I really liked the work you did on Spessasynth.

So I was wondering if you would be interested in helping out with something like that?

I specifically need help with frontend, and I want to combine the existing similar projects below into one nice interface:

https://github.com/stevenwaterman/musetree
https://github.com/bearpelican/musicautobot_vueapp

Check it out and please let me know if you can help. This is a pure open-source project which would be very useful to many people who use Symbolic Music AI for music composition and it would be a very nice contribution to the open-source community.

There is another developer who expressed desire to help out so there would be at least three of us:

https://github.com/SkyTNT/midi-model
https://huggingface.co/spaces/skytnt/midi-composer

I want to start working on it early next year so there is plenty of time to think about it.

Please let me know if you can help us with this project. I would really appreciate that regardless of your response.

Please email to me directly at alexlev61@proton.me or respond here if you want.

Most sincerely,

Alex.

PS. I really loved the latest stuff you added to Spessasynth. Great job!

**Comment by spessasus** [comment]
Hi Alex,

I'll think about it and reach out directly.

**Comment by asigalov61** [comment]
@spessasus Thank you very much.
