### ISSUE TITLE
Render audio to file

### ISSUE THREAD

**Issue by spessasus** [spessasus/SpessaSynth#5]
Allow users to render the audio to a wav file.
This will be really difficult since the sequencer is in the main thread and revolves around setInterval

**Comment by bastecklein** [comment]
Maybe take a look at how this project does it: https://github.com/ryohey/signal
Signal seems to convert MIDI to WAV very quickly

**Comment by spessasus** [comment]
I appreciate the suggestion, @bastecklein. I think moving everything to the audioWorkletGlobalScope and using OfflineAudioContext could work.

**Comment by spessasus** [comment]
After a complete internal rewrite, I'm happy to announce that SpessaSynth now supports this feature!
