### ISSUE TITLE
have current preset appear in middle of preset selection view

### ISSUE THREAD

**Issue by mrbumpy409** [spessasus/SpessaSynth#54]
When clicking on the current preset name to browse presets on the `github.io` page, the currently selected preset appears at the bottom of the list. This means the user has to scroll down in the list to select the next preset. It would be a nice enhancement to have the currently selected preset appear in the middle of the list so no scrolling is necessary to select the next available preset.

**Comment by spessasus** [comment]
Hi Christian,

I'll work on other issues, but this one depends on the browser as the preset selector uses HTML's native `<select>` element. So this is not really a bug.

Thanks for reporting the others though!

**Comment by mrbumpy409** [comment]
You have done a really fantastic job with this synth! Your SoundFont modulator support is really robust (it's a rare thing to see the whole spec implemented), and it handled almost everything GeneralUser GS 2.0 could throw at it. :smile:

**Comment by spessasus** [comment]
> You have done a really fantastic job with this synth! Your SoundFont modulator support is really robust (it's a rare thing to see the whole spec implemented), and it handled almost everything GeneralUser GS 2.0 could throw at it. 😄

Thank you! :D

**Comment by spessasus** [comment]
Hi,

I've created a completely new preset selector which addresses this issue and also adds a search bar!

I hope you like it : )

**Comment by mrbumpy409** [comment]
The new preset selector is very slick! Nicely done. :grin:
