### ISSUE TITLE
MIDI channel pan is too extreme

### ISSUE THREAD

**Issue by mrbumpy409** [spessasus/SpessaSynth#59]
### Version
`github.io` page (3.20.43)

### Description
While playing MIDI files, I noticed that the instruments were panned too wide. Through testing via live MIDI input, I was able to determine that the sound is 100% panned to the right when CC10 = 97, and 100% panned to the left when CC10 = 32. Full panning shouldn't be achieved until CC10 is at its min/max value of 0/127.

### Reproduction steps
1. Set a MIDI channel to CC10 = 97. Observe how the sound only comes out of the right speaker.
2. Set CC10 = 127. Notice there is no difference from CC10 = 97.

### Expected behavior
CC10 = 97 should not be fully panned to the right.

### MIDI files and SoundFonts
A really good way to hear this issue is to play `Jump!.mid` that comes with GeneralUser GS 2.0 and compare it with the audio recording made with FluidSynth.

**Comment by spessasus** [comment]
Hi,

Fluidsynth is not correct here. See https://github.com/FluidSynth/fluidsynth/issues/1395

Spessasynth uses 1000 correctly.

**Comment by spessasus** [comment]
PS: the version you've reported is out of date. Please clear the cache in your browser and reload the page.

**Comment by mrbumpy409** [comment]
Hi @spessasus, I have [created a video](https://youtu.be/dwMnbajwIc0) demonstrating the problem. Here is the MIDI and SF2 file used to create the test shown in the video: [panning test.zip](https://github.com/user-attachments/files/17343111/panning.test.zip)

**Comment by spessasus** [comment]
Hi @mrbumpy409,

thanks for the detailed video and the test files! Indeed spessasynth is the odd one here. I've changed the pan modulator amount from 1000 to 500 like in fluidsynth, and I rendered the test files. It now shows the curve identical to fluid's or BASS's. Can you test this change to confirm the fix? The branch is called [pan-fix-test](https://github.com/spessasus/SpessaSynth/tree/pan-fix-test).

PS: Have a great day too :)

**Comment by spessasus** [comment]
After more testing, I merged it into main. You're right, the previous solution sounded totally wrong. Thanks for the report!
If the panning is still incorrect, feel free to open another issue.

**Comment by mrbumpy409** [comment]
Thank you, @spessasus, everything sounds great!
