### ISSUE TITLE
[FEATURE REQUEST] Export to DLS, from SF2 -> DLS

### ISSUE THREAD

**Issue by gnaomo** [spessasus/SpessaSynth#64]
**Is your feature request related to a problem? Please describe.**
Would be cool to have a DLS export too, from SF2, may be something very difficult tho i have no idea

**Is your feature related to the sound library or the app/website?**
Sound library

**Describe the solution you'd like**
SF2 to DLS Convert, ability to export to a DLS file.

**Describe alternatives you've considered**
Awave Studio is the only solution I found but it's 90$ and the trial version has the export option disabled

**Additional context**

**Comment by spessasus** [comment]
Hm, that's an interesting idea! It shouldn't be too difficult to implement, except for the fact that there's not a thing like presets in DLS (only instruments, 1 zone deep, unlike 2 in SF2), so the program should add the values and zones manually. That's doable.

Though, I would need a DLS synth to test with. The only other one than spessa is Winamp's MIDI player. Can you name a DLS synth that I could test with?

Note: fluidsynth and synthfont both are not correctly implementing DLS parameters, so these don't count.

**Comment by spessasus** [comment]
According to the internet, only DLS 1 is supported there, but sf2 will use DLS 2 since 1 limits all parameters to the global zone.

But I'll try to implement your suggestion, I'll test it in Winamp.

**Comment by spessasus** [comment]
It's a bit more difficult than I thought... but I'm working on it. Check branch [write-dls](https://github.com/spessasus/SpessaSynth/tree/write-dls) for progress.

**Comment by spessasus** [comment]
Well, no. I've hit a roadblock. There's a hard limit on generators in an SF2 file (around 65k), and combining the zones (even smart parameter globalization) exceeds 100k on complex soundfonts like generaluserGS. Even if this will make a valid DLS file, it won't be able to be loaded by spessasynth.

**Comment by spessasus** [comment]
Hi,

I'm pleased to let you know that as of 3.23.6, winamp loads the DLS files exported by Spessasynth. Even as large as 1GB!
