### ISSUE TITLE
[FEATURE REQUEST] Earlier loading of the app

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#70]
**Is your feature request related to a problem? Please describe.**
Currently, the app waits for downloading the soundfont. If this is finished the app shows up.
It would be better in my opinion to show the app immediately and only hide the midi upload button or play button as long as the soundfont is not loaded.

**Is your feature related to the sound library or the app/website?**
Only related to the app/website.

**Describe the solution you'd like**
- Load the app GUI immediately and only hide the relevant buttons as long as the soundfont is not loaded.
- Unhide the buttons if the soundfont is loaded.

**Describe alternatives you've considered**
- Alternative: stay with the current approach

**Additional context**

**Comment by spessasus** [comment]
Hi,

I don't think that this would work, because pretty much everything would have to be hidden too, as:
- if there's no soundfont, there's no synth
- so there's no synth controller.
- so there's no keyboard
- so there's no settings

And even then, downloading only happens once. The browser saves the soundfont once it's downloaded so every new refresh is instant.

**Comment by TS53** [comment]
Ok, thanks. In my case it loads it again because I disable the browser caching per website (I also have to login on github each time), so I'm waiting a few seconds each time until the GUI appears. I thought that a default keyboard can get shown.
But I understand that if too much would be hidden, then this would not be an enhancement.

**Comment by spessasus** [comment]
> Ok, thanks. In my case it loads it again because I disable the browser caching per website (I also have to login on github each time), so I'm waiting a few seconds each time until the GUI appears. I thought that a default keyboard can get shown.
> But I understand that if too much would be hidden, then this would not be an enhancement.

Then consider downloading local edition. I too have disabled cache and local edition stores soundfonts in a folder and they get loaded automatically. Settings too, as JSON.

**Comment by TS53** [comment]
Ok, this is good to know, thanks!
