### ISSUE TITLE
[QUESTION] Is there any way to get the volume or loudness of each channel fast or before play start？

### ISSUE THREAD

**Issue by daxiangpanda** [spessasus/SpessaSynth#76]
[QUESTION] Is there any to get the volume or loudness of each channel fast or before play start？
I want to play midi using SpessaSynth，but sometimes the volume of each channel will be too big or too small,so that I can only change the volume myself. 
Is there any way or idea I can get the loudness before playing?

**Comment by spessasus** [comment]
Hi,

Volume can be influenced by many things, such as the velocity of the note, volume controllers and system exclusives.

But you can try using the eventHandler and listen to the `controllerchange` event for volume and expression controllers.
