### ISSUE TITLE
[QUESTION]Question about Real-Time ADSR Implementation in SpessaSynth

### ISSUE THREAD

**Issue by GL24TZ** [spessasus/SpessaSynth#82]
Hi,

Thank you for your amazing work on SpessaSynth! I have a question regarding the Modulator class and real-time envelope control. Is it possible to implement an ADSR (Attack, Decay, Sustain, Release) envelope in real-time for a SoundFont (SF2) instrument using this library?

If so, could you provide some guidance or an example of how to achieve this? For instance, modulating the volume or other parameters dynamically during playback to simulate an ADSR envelope.

Thank you for your time and for creating such a fantastic tool!

**Comment by spessasus** [comment]
Hi,

Spessasynth already supports the full soundfont Volume envelope:
- delay
- attack
- hold
- decay
- sustain
- release

To modify its parameters, you need to change the soundfont file itself. I recommend the Polyphone soundfont editor for that. There when in the **instrument** section (not preset, they are different!), you can see parameters such as "Vol Env Decay" (Volume envelope decay). This is what you're looking for. Change these values, save the soundfont and load it into Spessasynth and it should have the volume envelope all set up.

If you mean changing the envelope times in real time via MIDI controllers though, Spessasynth also supports that using the soundfont modulators.

In fact, there's already a default modulator in place that connects the MIDI release time controller to the volume envelope release time.

To achieve that, you need to use the soundfont editor again.

For Polyphone, at the bottom of the parameter table there's a section for modulators. You want to select your controller for controlling a stage as the primary source and leave source 2 as "No controller". Then set the destination to whichever stage you wish to modulate. (Such as Vol Env Attack). Then change the amount to the desired range of modulation. Note that the amount uses time cents, rather than seconds, so it's going to be exponential. I recommend trying an amount of 2000 and fine-tuning it from there.

Modulators essentially are just a fancy way of saying "this midi controller changes this by that much". By setting the amount to 2000, when you set the target controller to 127, the destination (envelope stage time in your case) will have 2000 added to it. For 64 it would be around 1000, for 0 it would be 0 and scaled like that for others.

I hope this helps, let me know if I got too technical here or something is unclear!

**Comment by GL24TZ** [comment]
Thank you for your response. I am using a very old version and I want to update to version 3.23.0 to perform the tests you advised, but I haven't been able to do it. These are the errors I have in the console: "b.js:48 Error loading worklet module: SyntaxError: The requested module './worklet_utilities/lowpass_filter.js' does not provide an export named 'applyLowpassFilter'
synthetizer.js:166 InvalidStateError: Failed to construct 'AudioWorkletNode': AudioWorkletNode cannot be created: The node name 'spessasynth-worklet-system' is not defined in AudioWorkletGlobalScope.
    at new Synthetizer (synthetizer.js:153:28)
    at initializeAudioContext (b.js:55:19)
    at async initAudioContextWithUserSoundFonts (b.js:32:17" `import { Synthetizer } from "./spessasynth_lib/synthetizer/synthetizer.js";
import { SoundFont2 } from "./spessasynth_lib/soundfont/soundfont_parser.js";
import { ShiftableByteArray } from "./spessasynth_lib/utils/shiftable_array.js";

let synths = []; // Array to store multiple synthesizers
let soundFonts = []; // Array to store SoundFont2 objects
let audioContext;
let allowedChannels = [{}, {}]; // Array to store allowed channels for each synthesizer

// Function to load a soundfont from a file
async function loadSoundFontFromFile(file) {
    try {
        const dataArray = new ShiftableByteArray(await file.arrayBuffer());
        return new SoundFont2(dataArray);
    } catch (error) {
        console.error("Error loading SoundFont:", error);
        return null;
    }
}

// Function to initialize the audio context with user-loaded soundfonts
async function initAudioContextWithUserSoundFonts(soundfontFiles) {
    audioContext = new AudioContext();

    // Load each soundfont from the files selected by the user
    for (let i = 0; i < soundfontFiles.length; i++) {
        if (soundfontFiles[i]) {
            const soundFont = await loadSoundFontFromFile(soundfontFiles[i]);
            if (soundFont) {
                soundFonts[i] = soundFont; // Store the SoundFont2 object
                console.log(`SoundFont ${i + 1} loaded:`, soundFont);
                await initializeAudioContext(soundFont, i);
                displaySoundList(i);
            } else {
                console.error(`Error loading SoundFont ${i + 1}`);
            }
        }
    }
}

// Function to initialize the audio context with a given soundfont
async function initializeAudioContext(soundFont, index) {
    // Add the worklet if supported
    if (audioContext.audioWorklet) {
        try {
            await audioContext.audioWorklet.addModule("./spessasynth_lib/synthetizer/worklet_system/channel_processor.js");
        } catch (error) {
            console.error("Error loading worklet module:", error);
        }
    } else {
        console.error("audioWorklet is not supported in this browser");
    }

    // Create the synthesizer with the given soundfont and store it in the array
    const synth = new Synthetizer(audioContext.destination, soundFont);
    synth.synthesisMode = "legacy"; // or "worklet"
    synths[index] = synth; // Add the synthesizer to the array at the corresponding index
}

// Función para obtener la lista de todos los presets en formato JSON
function getAllPresetsJSON(soundFontIndex) {
    const soundFont = soundFonts[soundFontIndex];
    if (!soundFont) return null;

    const presetList = [];
    const presets = soundFont.presets;

    if (!presets || presets.length === 0) {
        console.error(`No se encontraron presets para el SoundFont ${soundFontIndex + 1}`);
        return null;
    }

    for (let i = 0; i < presets.length; i++) {
        const preset = presets[i];
        if (preset) {
            // Usar presetName en lugar de name
            presetList.push({
                name: preset.presetName || `Preset ${i}`,
                program: preset.program,
                bank: preset.bank
            });
        }
    }

    return presetList; // Devolver la lista de presets como un array de objetos
}

// Función para mostrar la lista de sonidos en la página
function displaySoundList(soundFontIndex) {
    const presetList = getAllPresetsJSON(soundFontIndex);
    if (presetList) {
        const soundListElement = document.getElementById(`soundList${soundFontIndex + 1}`);
        if (soundListElement) {
            // Crear la tabla
            const table = document.createElement('table');
            table.innerHTML = `<thead>
                <tr>
                    <th>No.</th>
                    <th>Name</th>
                    <th>Program</th>
                    <th>Bank</th>
                </tr>
            </thead>
            <tbody>
                ${presetList.map((preset, index) => `
                    <tr>
                        <td>${index + 1}</td>
                        <td>${preset.name}</td>
                        <td>${preset.program}</td>
                        <td>${preset.bank}</td>
                    </tr>
                `).join('')}
            </tbody>`;

            // Limpiar el contenido anterior y añadir la nueva tabla
            soundListElement.innerHTML = '';
            soundListElement.appendChild(table);
        } else {
            console.error(`Elemento #soundList${soundFontIndex + 1} no encontrado`);
        }
    }
}

// Function to create channel checkboxes
function createChannelCheckboxes(containerId, soundfontIndex) {
    const container = document.getElementById(containerId);
    if (!container) {
        console.error(`Element #${containerId} not found`);
        return;
    }

    for (let i = 1; i <= 16; i++) {
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.id = `channel${soundfontIndex}_${i}`;
        checkbox.className = 'channel-checkbox';
        checkbox.checked = true; // By default, all channels are allowed

        const label = document.createElement('label');
        label.htmlFor = checkbox.id;
        label.textContent = `Channel ${i}`;

        container.appendChild(checkbox);
        container.appendChild(label);
        container.appendChild(document.createElement('br'));

        allowedChannels[soundfontIndex][i] = true;

        checkbox.addEventListener('change', function() {
            allowedChannels[soundfontIndex][i] = this.checked;
        });
    }
}

// Function to handle the "Select All" button
function handleSelectAll(buttonId, checkboxesContainerId, soundfontIndex) {
    const selectAllButton = document.getElementById(buttonId);
    const checkboxesContainer = document.getElementById(checkboxesContainerId);

    if (!selectAllButton || !checkboxesContainer) {
        console.error(`Element #${buttonId} or #${checkboxesContainerId} not found`);
        return;
    }

    selectAllButton.addEventListener('click', function() {
        const checkboxes = checkboxesContainer.querySelectorAll('input[type="checkbox"]');
        const allChecked = Array.from(checkboxes).every(cb => cb.checked);

        checkboxes.forEach((cb, index) => {
            cb.checked = !allChecked;
            allowedChannels[soundfontIndex][index + 1] = !allChecked;
        });
    });
}

// Create checkboxes for both soundfonts
createChannelCheckboxes('checkboxes1', 0);
createChannelCheckboxes('checkboxes2', 1);

// Handle "Select All" buttons
handleSelectAll('selectAll1', 'checkboxes1', 0);
handleSelectAll('selectAll2', 'checkboxes2', 1);

// Get reference to the start audio button
const startAudioButton = document.getElementById("startAudioButton");

// Add a click event to the button to start the audio
if (startAudioButton) {
    startAudioButton.addEventListener("click", function() {
        if (audioContext) {
            audioContext.resume();
        }
    });
} else {
    console.error("Start audio button not found");
}

// Get references to the file input elements
const soundfontInput1 = document.getElementById("soundfontInput1");
const soundfontInput2 = document.getElementById("soundfontInput2");

// Add change events to the file inputs to load the soundfonts selected by the user
[soundfontInput1, soundfontInput2].forEach((input, index) => {
    if (input) {
        input.addEventListener("change", function(event) {
            const files = [soundfontInput1.files[0], soundfontInput2.files[0]];
            if (files[index]) {
                // Initialize the audio context with the user-loaded soundfonts
                initAudioContextWithUserSoundFonts(files);
            }
        });
    } else {
        console.error(`SoundFont input ${index + 1} not found`);
    }
});

// Get reference to the select element
const selectMidiDevice = document.getElementById("midi_device_select");

// Connect the onchange event of the select to send MIDI messages to the selected device
navigator.requestMIDIAccess()
    .then(function(midiAccess) {
        // Get available MIDI devices
        const inputs = midiAccess.inputs.values();

        // Iterate over MIDI devices and add them to the select
        for (let input = inputs.next(); input && !input.done; input = inputs.next()) {
            const option = document.createElement("option");
            option.text = input.value.name;
            option.value = input.value.id;
            selectMidiDevice.add(option);
        }

        // Connect the onchange event of the select to send MIDI messages to the selected device
        selectMidiDevice.addEventListener("change", function(event) {
            const selectedDeviceId = event.target.value;
            const input = midiAccess.inputs.get(selectedDeviceId);
            if (input) {
                input.onmidimessage = function(event) {
                    // Get the channel from the MIDI message (the 4 least significant bits of the first byte)
                    const channel = (event.data[0] & 0xF) + 1;

                    // Send the MIDI message only to synthesizers that have this channel allowed
                    synths.forEach((synth, index) => {
                        if (allowedChannels[index][channel]) {
                            synth.sendMessage(event.data);
                        }
                    });
                };
            }
        });
    })
    .catch(error => {
        console.error("Error accessing MIDI devices:", error);
    });
`

**Comment by GL24TZ** [comment]
`import { Synthetizer } from "./spessasynth_lib/synthetizer/synthetizer.js";
import { SoundFont2 } from "./spessasynth_lib/soundfont/soundfont_parser.js";
import { ShiftableByteArray } from "./spessasynth_lib/utils/shiftable_array.js";

let synths = []; // Array to store multiple synthesizers
let soundFonts = []; // Array to store SoundFont2 objects
let audioContext;
let allowedChannels = [{}, {}]; // Array to store allowed channels for each synthesizer

// Function to load a soundfont from a file
async function loadSoundFontFromFile(file) {
    try {
        const dataArray = new ShiftableByteArray(await file.arrayBuffer());
        return new SoundFont2(dataArray);
    } catch (error) {
        console.error("Error loading SoundFont:", error);
        return null;
    }
}

// Function to initialize the audio context with user-loaded soundfonts
async function initAudioContextWithUserSoundFonts(soundfontFiles) {
    audioContext = new AudioContext();

    // Load each soundfont from the files selected by the user
    for (let i = 0; i < soundfontFiles.length; i++) {
        if (soundfontFiles[i]) {
            const soundFont = await loadSoundFontFromFile(soundfontFiles[i]);
            if (soundFont) {
                soundFonts[i] = soundFont; // Store the SoundFont2 object
                console.log(`SoundFont ${i + 1} loaded:`, soundFont);
                await initializeAudioContext(soundFont, i);
                displaySoundList(i);
            } else {
                console.error(`Error loading SoundFont ${i + 1}`);
            }
        }
    }
}

// Function to initialize the audio context with a given soundfont
async function initializeAudioContext(soundFont, index) {
    // Add the worklet if supported
    if (audioContext.audioWorklet) {
        try {
            await audioContext.audioWorklet.addModule("./spessasynth_lib/synthetizer/worklet_system/channel_processor.js");
        } catch (error) {
            console.error("Error loading worklet module:", error);
        }
    } else {
        console.error("audioWorklet is not supported in this browser");
    }

    // Create the synthesizer with the given soundfont and store it in the array
    const synth = new Synthetizer(audioContext.destination, soundFont);
    synth.synthesisMode = "legacy"; // or "worklet"
    synths[index] = synth; // Add the synthesizer to the array at the corresponding index
}

// Función para obtener la lista de todos los presets en formato JSON
function getAllPresetsJSON(soundFontIndex) {
    const soundFont = soundFonts[soundFontIndex];
    if (!soundFont) return null;

    const presetList = [];
    const presets = soundFont.presets;

    if (!presets || presets.length === 0) {
        console.error(`No se encontraron presets para el SoundFont ${soundFontIndex + 1}`);
        return null;
    }

    for (let i = 0; i < presets.length; i++) {
        const preset = presets[i];
        if (preset) {
            // Usar presetName en lugar de name
            presetList.push({
                name: preset.presetName || `Preset ${i}`,
                program: preset.program,
                bank: preset.bank
            });
        }
    }

    return presetList; // Devolver la lista de presets como un array de objetos
}

// Función para mostrar la lista de sonidos en la página
function displaySoundList(soundFontIndex) {
    const presetList = getAllPresetsJSON(soundFontIndex);
    if (presetList) {
        const soundListElement = document.getElementById(`soundList${soundFontIndex + 1}`);
        if (soundListElement) {
            // Crear la tabla
            const table = document.createElement('table');
            table.innerHTML = `<thead>
                <tr>
                    <th>No.</th>
                    <th>Name</th>
                    <th>Program</th>
                    <th>Bank</th>
                </tr>
            </thead>
            <tbody>
                ${presetList.map((preset, index) => `
                    <tr>
                        <td>${index + 1}</td>
                        <td>${preset.name}</td>
                        <td>${preset.program}</td>
                        <td>${preset.bank}</td>
                    </tr>
                `).join('')}
            </tbody>`;

            // Limpiar el contenido anterior y añadir la nueva tabla
            soundListElement.innerHTML = '';
            soundListElement.appendChild(table);
        } else {
            console.error(`Elemento #soundList${soundFontIndex + 1} no encontrado`);
        }
    }
}

// Function to create channel checkboxes
function createChannelCheckboxes(containerId, soundfontIndex) {
    const container = document.getElementById(containerId);
    if (!container) {
        console.error(`Element #${containerId} not found`);
        return;
    }

    for (let i = 1; i <= 16; i++) {
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.id = `channel${soundfontIndex}_${i}`;
        checkbox.className = 'channel-checkbox';
        checkbox.checked = true; // By default, all channels are allowed

        const label = document.createElement('label');
        label.htmlFor = checkbox.id;
        label.textContent = `Channel ${i}`;

        container.appendChild(checkbox);
        container.appendChild(label);
        container.appendChild(document.createElement('br'));

        allowedChannels[soundfontIndex][i] = true;

        checkbox.addEventListener('change', function () {
            allowedChannels[soundfontIndex][i] = this.checked;
        });
    }
}

// Function to handle the "Select All" button
function handleSelectAll(buttonId, checkboxesContainerId, soundfontIndex) {
    const selectAllButton = document.getElementById(buttonId);
    const checkboxesContainer = document.getElementById(checkboxesContainerId);

    if (!selectAllButton || !checkboxesContainer) {
        console.error(`Element #${buttonId} or #${checkboxesContainerId} not found`);
        return;
    }

    selectAllButton.addEventListener('click', function () {
        const checkboxes = checkboxesContainer.querySelectorAll('input[type="checkbox"]');
        const allChecked = Array.from(checkboxes).every(cb => cb.checked);

        checkboxes.forEach((cb, index) => {
            cb.checked = !allChecked;
            allowedChannels[soundfontIndex][index + 1] = !allChecked;
        });
    });
}

// Create checkboxes for both soundfonts
createChannelCheckboxes('checkboxes1', 0);
createChannelCheckboxes('checkboxes2', 1);

// Handle "Select All" buttons
handleSelectAll('selectAll1', 'checkboxes1', 0);
handleSelectAll('selectAll2', 'checkboxes2', 1);

// Get reference to the start audio button
const startAudioButton = document.getElementById("startAudioButton");

// Add a click event to the button to start the audio
if (startAudioButton) {
    startAudioButton.addEventListener("click", function () {
        if (audioContext) {
            audioContext.resume();
        }
    });
} else {
    console.error("Start audio button not found");
}

// Get references to the file input elements
const soundfontInput1 = document.getElementById("soundfontInput1");
const soundfontInput2 = document.getElementById("soundfontInput2");

// Add change events to the file inputs to load the soundfonts selected by the user
[soundfontInput1, soundfontInput2].forEach((input, index) => {
    if (input) {
        input.addEventListener("change", function (event) {
            const files = [soundfontInput1.files[0], soundfontInput2.files[0]];
            if (files[index]) {
                // Initialize the audio context with the user-loaded soundfonts
                initAudioContextWithUserSoundFonts(files);
            }
        });
    } else {
        console.error(`SoundFont input ${index + 1} not found`);
    }
});

// Get reference to the select element
const selectMidiDevice = document.getElementById("midi_device_select");

// Connect the onchange event of the select to send MIDI messages to the selected device
navigator.requestMIDIAccess()
    .then(function (midiAccess) {
        // Get available MIDI devices
        const inputs = midiAccess.inputs.values();

        // Iterate over MIDI devices and add them to the select
        for (let input = inputs.next(); input && !input.done; input = inputs.next()) {
            const option = document.createElement("option");
            option.text = input.value.name;
            option.value = input.value.id;
            selectMidiDevice.add(option);
        }

        // Connect the onchange event of the select to send MIDI messages to the selected device
        selectMidiDevice.addEventListener("change", function (event) {
            const selectedDeviceId = event.target.value;
            const input = midiAccess.inputs.get(selectedDeviceId);
            if (input) {
                input.onmidimessage = function (event) {
                    // Get the channel from the MIDI message (the 4 least significant bits of the first byte)
                    const channel = (event.data[0] & 0xF) + 1;

                    // Send the MIDI message only to synthesizers that have this channel allowed
                    synths.forEach((synth, index) => {
                        if (allowedChannels[index][channel]) {
                            synth.sendMessage(event.data);
                        }
                    });
                };
            }
        });
    })
    .catch(error => {
        console.error("Error accessing MIDI devices:", error);
    });
`

**Comment by spessasus** [comment]
Did you remember to copy the new worklet_processor.min.js to your target folder? Also, it seems that you're still using the old synthesizer initialization. You need to pass an ArrayBuffer to it, rather than a SoundFont2 object. Reading the documentation and adjusting the code you've provided should resolve the problem :)

**Comment by spessasus** [comment]
Hi.
It's been a month, so I'm closing this issue. Feel free to open another one or comment on this one if the problem persists and I'll reopen it.
