### ISSUE TITLE
[BUG] Title does not work with Unicode

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#84]
### Version
`github.io` page

### Description
The title of MIDI file is not displayed as expected when the title contains unicode.

### Reproduction steps
1. Create a file called `ö.mid`
2. Upload it
3. Both the Title and the "Title of the Tab" can not display it correctly. It is only displayed correctly in the filename `ö.mid`.

I think the relevant HTML is `<h1 id="title" translate-path="locale.demoTitleMessage">...</h1>`

### Expected behavior
Expexted behavior would be that the Title also handles unicode.

**Comment by spessasus** [comment]
SpessaSynth supports many encodings, not just UTF-8. To make your file have the correct title, you need to select the correct code page:
![image](https://github.com/user-attachments/assets/672c035b-7db9-4461-b32e-462b280276f3)

As you can see, with **windows-1250** selected, ö appears correctly.

**Comment by TS53** [comment]
Thanks, it works after setting the encoding!

**Comment by spessasus** [comment]
I've fixed it properly, should work with all encodings now :)
