### ISSUE TITLE
[BUG] File drag-n-drop handler not staying still

### ISSUE THREAD

**Issue by pachuco** [spessasus/SpessaSynth#85]
### Version
Livedemo from github.

### Description
Drag-n-drop handler turning on and off repeatedly on mouseover with file in tow.
File load success depends on whether you manage to hit the handler with the dropped file!

### Reproduction steps
Try to load file via drag-n-drop.

### Expected behavior
Drag-n-drop handler should remain on while file is being dragged over browser, not epileptically spaz out.

### Screenshots
N/A

### MIDI files and SoundFonts
N/A

### Environment
XP x86 PC, Chrome-based [Supermium](https://github.com/win32ss/supermium) browser, version 126.0.6478.260 R6.
May or may not be a bug of the browser!

### Additional context
N/A

**Comment by spessasus** [comment]
Hi,
thanks for the bug report. I can confirm this happens on the stock Chromium as well. I'll look into it.

**Comment by spessasus** [comment]
I've just committed a fix for this, a very simple one at that!
Let me know if it works now (v3.23.8). If not, I'll reopen this issue.

**Comment by pachuco** [comment]
It works fine now.
