### ISSUE TITLE
[BUG] ASS subtitle bugs

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#88]
I will add smaller issues here I found with ASS subtitles after the merging of ASS subtitle into master branch:

- ~Prio high: When one subtitle is loaded successfully and after this in the same song we load a differnt subtitle this works as long as we don't have an embedded font. When we load the first ASS subtitle with an embedded font this one will also work but after this no subtitle with an _embedded_ font works again besides the same subtitle. It seems, the embedded font will then be used for all other embedded subtitles but this will not work because the embedded subtitle is _subsetted_. That means when the subset of first font does not has letter "t" in the text, the font will not have this letter. When the next subtitle with embedded font has the same font but different text, e.g. letter "t", it reqires its own subset font. After the first loading of embedded font we can correctly load subtitles without an embedded font but not a single different subtitle that also has an embedded font. It seems to be a reset problem.
Note: it's only about the embedded font. When a new embedded font subtitle with different text is loaded, the different text is displayed as expected. It just does not load the expected new embedded font.~
I have seen, you have fixed this already in a new [commit](https://github.com/spessasus/SpessaSynth/commit/b6d7671357c89c40df3a37cb1fc9388fdc9a29f1) and it works now!

- Prio middle: Parser: when the ASS subtitle `Events` section does _not_ end with a newline, it will not work. With libass it works normally.
Just adding a newline to the end will make the subtitle work as expected. For example, when the line ends with `{\K400}word.` and no new line follows, it will throw: `Uncaught (in promise) Error: Section [Events] not found!`

- Prio low: when we pause a song and a subtitle is loaded and a few words are already "red" at this position and if we now switch the ESC button a few times to hide and unhide, it will stay this color the first times, but after 1-5 times or so it suddenly becomes completely white text. Expectation: stay half red all the time when switching ESC buttons like the first few times. Note that this will only be visible when it is still paused.

- Enhancement: the black-transparent rectangle bounding box is too near at the char border. For example the first letter has the same border like the rectangle. In my opinion, it would be better to start/end the bounding box ca. 1 pt before, after, over and under the char boundaries.

Here is an additional test subtitle with different embedded font and different text:
[DunkleWolkEmbedOneLine.zip](https://github.com/user-attachments/files/18238452/DunkleWolkEmbedOneLine.zip)

**Comment by spessasus** [comment]
Middle prio should be fixed now.

**Comment by TS53** [comment]
Yes, it works now, thank you!

**Comment by spessasus** [comment]
Low prio should be fixed now.

**Comment by TS53** [comment]
Yes, works good, thank you!

**Comment by spessasus** [comment]
I don't get the last one. Maybe some screenshots please?

**Comment by TS53** [comment]
A few hours ago, I saw a good example, now this is the best I can reproduce. It is probably font dependend:
![rectangle](https://github.com/user-attachments/assets/e237cc72-d090-4023-aa86-ceb60d944a80)

The black rectangle behindt the text to make the text more readable, sometimes starts exactly with the first letter instead of 1 pt before to make it more readable. If it starts with the same first pixel of the letter, the first letter becomes difficult to read with some fonts.

**Comment by spessasus** [comment]
Alright, I've added some padding. Is it better?

**Comment by TS53** [comment]
Yes, it's good now, thank you!

**Comment by spessasus** [comment]
Glad to hear that. Happy Holidays!

**Comment by TS53** [comment]
Thank you, I wish you also happy holidays!🎄
