### ISSUE TITLE
[BUG] Changing the position at pause starts playing

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#90]
### Version
- Website

### Description & Reproduction steps
- Start a MIDI, pause it at some point, press <- or -> to change the position. Immediately after the position change the midi starts playing although it was in pause mode before.

### Expected behavior
- change the position like it does but stay in pause mode instead of playing

**Comment by spessasus** [comment]
This is intentional. Feel free to read #62 for more.
