### ISSUE TITLE
[BUG] ASS subtitles: some embedded fonts do not work

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#91]
Some embedded fonts work without problems, others don't work at all: in the Firefox console we can then always read something like `downloadable font: rejected by sanitizer ...`. In the following, I will add an embedded font from Google Fonts that don't work on the website. I don't subset it (`assfonts.exe -e` option) to make sure that the bug is most likely not related to `assfonts` tool.
The font does not work on the website, but it works with libass (for example when adding them via VLC as subtitle).

I assume the following should hold: if the font is not subsetted and then embedded and uploaded to the website, the font is then uploaded to a blob url. When I download this, the downloaded font should be the same as the original one (same checksum). But it seems to not always be the case (but maybe my assumption is wrong, I don't have good frontend knowledge).

I can imagine that the decoding of the UUencoding maybe is not always correct or that those fonts indeed are problematic and the font checks are very strict. But since I download them from Google Fonts and they work on this page, it rather seems to be a decoding problem.

From my first blob comparisons, it seems the blob starts with the original content but it then ends at some point (thus, the file is shorter, smaller file size).

Example Font [Caveat](https://fonts.google.com/specimen/Caveat) (Static and Variable font both work with VLC, full font, no subset)
[SubtitlesWithCaveatFont.zip](https://github.com/user-attachments/files/18251569/SubtitlesWithCaveatFont.zip)

It seems that for the given font the `font.data` is already too short before it gets decoded.

**Comment by spessasus** [comment]
All the attached fonts work with the latest commit, thanks for the report!

PS: Are you using Local Edition?

**Comment by TS53** [comment]
Thanks for the fix! Yes, I made the console.log edits in the local edition
