### ISSUE TITLE
[BUG] Warnings when rendering ASS subtitles

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#92]
Not really a bug, but maybe unexpected warnings:
The subtitles look as expected but with each new text block that is rendered from the ASS subtitle new warnings appear.
Tested with Firefox.

![warnings](https://github.com/user-attachments/assets/18d96201-bee2-487e-81d2-2f8e0dde99af)

**Comment by spessasus** [comment]
Can't reproduce with Arial, nor playwringt, nor Caveat (both versions). Can I have the ASS file?

**Comment by TS53** [comment]
You can just use the first ASS subtitle without embedded font, the website URL and the first MIDI. But the warnings will not be there at the beginning. After a few seconds they start and become more. Firefox 133.0.3

Ah, I see, you have to turn on the "CSS" window in the log:
![CSS window](https://github.com/user-attachments/assets/88d92e0e-960d-4b59-b9be-9660f276d795)

**Comment by spessasus** [comment]
I've fixed it. Thanks for the report! I didn't even know about the CSS error tab before :)
