### ISSUE TITLE
[BUG] callback for addOnSongChangeEvent is called twice

### ISSUE THREAD

**Issue by birkeeper** [spessasus/SpessaSynth#93]
### Version
`spessasynth_lib` (tag v3.23.0) downloaded via `git clone`. The library is included into the github project as a submodule.

### Description
After registering a callback function with `sequencer.addOnSongChangeEvent()`, when the song is changed, the callback is called twice.

### Reproduction steps
Run `advanced_demo.js`. Add `console.log("song changed"); ` to the callback function. This output will appear twice in the console when the song is changed.

### Expected behavior
Callback should only be called once.

### Environment
This behaviour has been observed when using Chrome browser version 131.0.6778.205 on a Windows 11 system

**Comment by spessasus** [comment]
Hi,

Thanks for the bug report! `addOnSongChangeEvent` called the callback function on being set for some reason. Not really sure about that one, it's fixed now! (3.23.13)

**Comment by birkeeper** [comment]
Thanks
